name: 💡 Feature
description: Nova funcionalidade ou melhoria
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema / motivação
      description: Que necessidade essa feature resolve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
      description: Como a feature deveria funcionar?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de aceite
    validations:
      required: true
